import type { ComponentType } from "react";
import {
  TbApi,
  TbBrandRedux,
  TbKey,
  TbLayersLinked,
  TbRocket,
  TbStack2,
} from "react-icons/tb";
import {
  SiAmazonwebservices,
  SiDocker,
  SiExpress,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiGo,
  SiGraphql,
  SiLinux,
  SiMongodb,
  SiMongoose,
  SiMysql,
  SiNestjs,
  SiNextdotjs,
  SiNginx,
  SiNodedotjs,
  SiPostgresql,
  SiPostman,
  SiPrisma,
  SiReact,
  SiRedis,
  SiSocketdotio,
  SiStripe,
  SiSwagger,
  SiTailwindcss,
  SiTypescript,
  SiVite,
  SiWebrtc,
} from "react-icons/si";

export interface TechItem {
  name: string;
  icon: ComponentType<{ className?: string; "aria-hidden"?: boolean }>;
}

/** Primary stack shown in hero — order is intentional (backend first). */
export const showcaseTech: TechItem[] = [
  { name: "Node.js", icon: SiNodedotjs },
  { name: "NestJS", icon: SiNestjs },
  { name: "Express.js", icon: SiExpress },
  { name: "TypeScript", icon: SiTypescript },
  { name: "PostgreSQL", icon: SiPostgresql },
  { name: "Redis", icon: SiRedis },
  { name: "MongoDB", icon: SiMongodb },
  { name: "Next.js", icon: SiNextdotjs },
  { name: "React", icon: SiReact },
  { name: "Prisma", icon: SiPrisma },
  { name: "Docker", icon: SiDocker },
  { name: "AWS", icon: SiAmazonwebservices },
  { name: "GitHub Actions", icon: SiGithubactions },
  { name: "Socket.IO", icon: SiSocketdotio },
  { name: "Stripe", icon: SiStripe },
  { name: "MySQL", icon: SiMysql },
  { name: "Nginx", icon: SiNginx },
  { name: "Tailwind CSS", icon: SiTailwindcss },
];

const alias: Record<string, ComponentType<{ className?: string }>> = {
  "node.js": SiNodedotjs,
  express: SiExpress,
  "express.js": SiExpress,
  typescript: SiTypescript,
  nestjs: SiNestjs,
  "nestjs 11": SiNestjs,
  go: SiGo,
  graphql: SiGraphql,
  react: SiReact,
  "react 19": SiReact,
  "react 18": SiReact,
  "next.js": SiNextdotjs,
  "next.js 16": SiNextdotjs,
  "next.js 15": SiNextdotjs,
  mongodb: SiMongodb,
  mongoose: SiMongoose,
  postgresql: SiPostgresql,
  "postgresql 17": SiPostgresql,
  prisma: SiPrisma,
  "prisma 7": SiPrisma,
  redis: SiRedis,
  "redis 7": SiRedis,
  docker: SiDocker,
  aws: SiAmazonwebservices,
  "aws s3": SiAmazonwebservices,
  "github actions": SiGithubactions,
  "ci/cd": TbRocket,
  cicd: TbRocket,
  "socket.io": SiSocketdotio,
  stripe: SiStripe,
  mysql: SiMysql,
  nginx: SiNginx,
  linux: SiLinux,
  tailwind: SiTailwindcss,
  "tailwind css": SiTailwindcss,
  "tailwind css 4": SiTailwindcss,
  jwt: TbKey,
  rbac: TbKey,
  rest: TbApi,
  "rest apis": TbApi,
  "rest api": TbApi,
  swagger: SiSwagger,
  openapi: SiSwagger,
  "swagger/openapi": SiSwagger,
  "openapi / swagger": SiSwagger,
  bullmq: TbStack2,
  zod: TbStack2,
  git: SiGit,
  github: SiGithub,
  postman: SiPostman,
  "tanstack query": TbApi,
  "redux toolkit": TbBrandRedux,
  redux: TbBrandRedux,
  "rtk query": TbBrandRedux,
  zustand: TbLayersLinked,
  vite: SiVite,
  webrtc: SiWebrtc,
};

export function iconForTech(name: string) {
  return alias[name.toLowerCase()] ?? null;
}
